spring.application.name=identity-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/identity_db
spring.datasource.username=identity_user
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.kafka.bootstrap-servers=localhost:9092

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.jwt.secret=${JWT_SECRET}
spring.jwt.expiration-minutes=60
