server:
  port: 8084

spring:
  application:
    name: attendance-service
  datasource:
    url: jdbc:postgresql://localhost:5436/attendance_db
    username: attendance_user
    password: attendance_pass
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

attendance:
  kafka:
    topic: attendance.events

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
