server:
  port: 8083

spring:
  application:
    name: employee-service

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5435/employee_db
    username: employee_user
    password: employee_pass

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092

employee:
  kafka:
    topic: employee-events

logging:
  level:
    org.flywaydb: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info